"""empty message

Revision ID: 50e96bd3fa22
Revises: c0d30db0f0f1
Create Date: 2021-07-12 19:53:37.629202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50e96bd3fa22'
down_revision = 'c0d30db0f0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
